[package]
name = "omflib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
num-derive = "0.4.2"
num-traits = "0.2.19"
pretty-hex = "0.4.1"
